# based on https://github.com/bitnami/containers/blob/f75effba29a8029a866c9b41bcf444c10fe6e98f/bitnami/opencart/docker-compose.yml
version: '1'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    ports:
      - '${OPENCART_DATABASE_PORT_NUMBER}:${OPENCART_DATABASE_PORT_NUMBER}'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${OPENCART_DATABASE_USER}
      - MARIADB_PASSWORD=${OPENCART_DATABASE_PASSWORD}
      - MARIADB_DATABASE=${OPENCART_DATABASE_NAME}
      - MARIADB_PORT_NUMBER=${OPENCART_DATABASE_PORT_NUMBER}
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:3.0.3-8
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_USERNAME=${OPENCART_USERNAME}
      - OPENCART_PASSWORD=${OPENCART_PASSWORD}
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=${OPENCART_DATABASE_PORT_NUMBER}
      - OPENCART_DATABASE_USER=${OPENCART_DATABASE_USER}
      - OPENCART_DATABASE_PASSWORD=${OPENCART_DATABASE_PASSWORD}
      - OPENCART_DATABASE_NAME=${OPENCART_DATABASE_NAME}
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local